name: Build Linux and Windows

on:
  push:
    branches:
      - main  # Triggered when changes are pushed to the `main` branch.

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Linux executable
        run: |
          .venv/bin/pyinstaller --onefile --name=agent agent/__main__.py
          .venv/bin/pyinstaller --onefile --name=bot bot/__main__.py

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts-linux-${{ github.sha }}
          path: dist/*

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          .\.venv\Scripts\activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Windows executable
        run: |
          .\.venv\Scripts\pyinstaller.exe --onefile --name=agent agent\__main__.py
          .\.venv\Scripts\pyinstaller.exe --onefile --name=bot bot\__main__.py

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts-windows-${{ github.sha }}
          path: dist/*
