name: Build Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache virtualenv
        uses: actions/cache@v4
        with:
          path: .venv
          key: windows-venv-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: windows-venv-

      - name: Install dependencies
        run: |
          python -m venv .venv
          .\.venv\Scripts\activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install NSIS
        run: choco install nsis -y

      - name: Set version
        run: |
          $base_version = (Select-String -Path pyproject.toml -Pattern '(?<=version = \")[^\"]*').Matches.Groups[0].Value
          $full_version = "$base_version-${env:GITHUB_RUN_NUMBER}"
          echo "VERSION=$full_version" >> $Env:GITHUB_ENV

      - name: Build executables
        run: |
          .\.venv\Scripts\pyinstaller.exe --onefile --name=agent agent\__main__.py
          .\.venv\Scripts\pyinstaller.exe --onefile --name=bot bot\__main__.py

      - name: Package Windows
        run: |
          mkdir release
          & "C:\\Program Files (x86)\\NSIS\\makensis.exe" .\installer\agent_installer.nsi /DVERSION=${{ env.VERSION }}
          & "C:\\Program Files (x86)\\NSIS\\makensis.exe" .\installer\bot_installer.nsi /DVERSION=${{ env.VERSION }}
          Move-Item -Path ".\installer\installer-agent-windows-v${{ env.VERSION }}.exe" -Destination ".\release\"
          Move-Item -Path ".\installer\installer-bot-windows-v${{ env.VERSION }}.exe" -Destination ".\release\"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-windows-${{ env.VERSION }}
          path: release/*
