name: Build Linux and Windows

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache virtualenv
        uses: actions/cache@v4
        with:
          path: .venv
          key: linux-venv-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: linux-venv-

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install fpm
        run: |
          sudo apt-get update
          sudo apt-get install ruby-dev -y
          sudo gem install --no-document fpm

      - name: Set version
        run: |
          base_version=$(grep -Po '(?<=version = \")[^\"]*' pyproject.toml)
          VERSION="${base_version}-${GITHUB_RUN_NUMBER}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build executables
        run: |
          .venv/bin/pyinstaller --onefile --name=agent agent/__main__.py
          .venv/bin/pyinstaller --onefile --name=bot bot/__main__.py

      - name: Package Linux
        run: |
          mkdir -p deb_pkg/opt/agent deb_pkg/opt/bot
          cp dist/agent deb_pkg/opt/agent/
          cp agent/config.json deb_pkg/opt/agent/
          cp dist/bot deb_pkg/opt/bot/
          cp bot/config.json deb_pkg/opt/bot/
          mkdir -p deb_pkg/etc/systemd/system
          cp ./etc/systemd/system/agent.service deb_pkg/etc/systemd/system/
          cp ./etc/systemd/system/bot.service deb_pkg/etc/systemd/system/
          fpm -s dir -t deb -n agent -v ${{ env.VERSION }} \
            --after-install scripts/after-install-agent.sh \
            deb_pkg/opt/agent/ deb_pkg/etc/systemd/system/

          fpm -s dir -t deb -n bot -v ${{ env.VERSION }} \
            --after-install scripts/after-install-bot.sh \
            deb_pkg/opt/bot/ deb_pkg/etc/systemd/system/

          mkdir -p release
          mv agent_${{ env.VERSION }}_amd64.deb release/
          mv bot_${{ env.VERSION }}_amd64.deb release/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-linux-${{ env.VERSION }}
          path: release/*

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache virtualenv
        uses: actions/cache@v4
        with:
          path: .venv
          key: windows-venv-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: windows-venv-

      - name: Install dependencies
        run: |
          python -m venv .venv
          .\.venv\Scripts\activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install NSIS
        run: choco install nsis -y

      - name: Set version
        run: |
          $base_version = (Select-String -Path pyproject.toml -Pattern '(?<=version = \")[^\"]*').Matches.Groups[0].Value
          $full_version = "$base_version-${env:GITHUB_RUN_NUMBER}"
          echo "VERSION=$full_version" >> $Env:GITHUB_ENV

      - name: Build executables
        run: |
          .\.venv\Scripts\pyinstaller.exe --onefile --name=agent agent\__main__.py
          .\.venv\Scripts\pyinstaller.exe --onefile --name=bot bot\__main__.py

      - name: Package Windows
        run: |
          mkdir release
          & "C:\\Program Files (x86)\\NSIS\\makensis.exe" .\installer\agent_installer.nsi /DVERSION=${{ env.VERSION }}
          & "C:\\Program Files (x86)\\NSIS\\makensis.exe" .\installer\bot_installer.nsi /DVERSION=${{ env.VERSION }}
          Move-Item -Path ".\installer\installer-agent-windows-v${{ env.VERSION }}.exe" -Destination ".\release\"
          Move-Item -Path ".\installer\installer-bot-windows-v${{ env.VERSION }}.exe" -Destination ".\release\"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-windows-${{ env.VERSION }}
          path: release/*


  publish:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]

    permissions:
      contents: write  # Required to create and push tags
      pull-requests: write  # Required for working with pull requests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version environment variable
        run: |
          base_version=$(grep -Po '(?<=version = \")[^\"]*' pyproject.toml)
          VERSION="${base_version}-${GITHUB_RUN_NUMBER}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-linux-${{ env.VERSION }}

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-windows-${{ env.VERSION }}

      - name: Check if tag exists and create or update tag
        run: |
          # Create the tag if it doesn't exist, or force update if it does
          git fetch --tags
          if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1
          then
            echo "Tag v${{ env.VERSION }} already exists. Updating tag."
            git tag -d "v${{ env.VERSION }}"
            git tag "v${{ env.VERSION }}"
          else
            echo "Creating new tag v${{ env.VERSION }}"
            git tag "v${{ env.VERSION }}"
          fi
          git push origin "v${{ env.VERSION }}" --force  # Push the tag to GitHub, force update if needed

      - name: List files in release folder
        run: |
          echo "Listing files in release folder:"
          ls -al ./

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            installer-agent-windows-v${{ env.VERSION }}.exe
            installer-bot-windows-v${{ env.VERSION }}.exe
            agent_${{ env.VERSION }}_amd64.deb
            bot_${{ env.VERSION }}_amd64.deb
          tag_name: v${{ env.VERSION }}  # Use the tag created/updated in the previous step
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
