name: CI Pipeline

on:
  push:
    branches:
      - main  # Запускать на пуш в main
  pull_request:
    branches:
      - main  # Запускать при создании Pull Request в main

jobs:
  build:
    runs-on: ${{ matrix.os }}  # Параллельная сборка для Windows и Linux
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]  # Параллельная сборка для Windows и Linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install bump2version
          pip install -r requirements.txt

      - name: Install fpm
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install ruby-dev  # Устанавливаем зависимости для fpm
          sudo gem install --no-document fpm  # Устанавливаем fpm
          echo "fpm installed"

      - name: Set version environment variable for win
        if: runner.os == 'Windows'  # Условие для Windows
        run: |
          $version = (Select-String -Pattern '(?<=version = ")[^"]*' pyproject.toml).Matches.Groups[0].Value
          echo "VERSION=$version" >> $Env:GITHUB_ENV
          echo "Version set to: $version"

      - name: Set version environment variable for linux
        if: runner.os == 'Linux'  # Условие для Linux
        run: |
          VERSION=$(grep -Po '(?<=version = ")[^"]*' pyproject.toml)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Version set to: $VERSION"  # Используем локальную переменную

      - name: Build and package for Windows
        if: runner.os == 'Windows'  # Условие для Windows
        run: |
            # Создание .exe файлов с помощью PyInstaller
            pyinstaller --onefile --name=agent.exe agent/__main__.py
            pyinstaller --onefile --name=bot.exe bot/__main__.py
          
            # Проверка версии
            echo "version $env:VERSION !!!"
  
            # Установщик Windows с помощью NSIS для агента
            echo "!include 'MUI2.nsh'" > agent_installer.nsi
            echo "Outfile 'installer-agent-windows-v$env:VERSION.exe'" >> agent_installer.nsi
            echo "InstallDir \$TEMP" >> agent_installer.nsi
            echo "Section" >> agent_installer.nsi
            echo "  SetOutPath \$INSTDIR" >> agent_installer.nsi
            echo "  File dist\\agent.exe" >> agent_installer.nsi
            echo "  File agent\\config.json" >> agent_installer.nsi
            echo "  WriteRegStr HKLM 'SOFTWARE\\Agent' 'Path' '\$INSTDIR\\agent.exe'" >> agent_installer.nsi
            echo "  ExecWait '\$INSTDIR\\agent.exe --config \$INSTDIR\\
