name: Publish Release

on:
  pull_request:
    types:
      - closed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true  # Проверяем, что PR был слит

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set version environment variable
        run: |
          base_version=$(grep -Po '(?<=version = \")[^\"]*' pyproject.toml)
          VERSION="${base_version}-${GITHUB_RUN_NUMBER}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Download Linux artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts-linux-${{ env.VERSION }}

      - name: Download Windows artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts-windows-${{ env.VERSION }}

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/installer-agent-windows-v${{ env.VERSION }}.exe
            release/installer-bot-windows-v${{ env.VERSION }}.exe
            release/agent-${{ env.VERSION }}-amd64.deb
            release/bot-${{ env.VERSION }}-amd64.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install bump2version
        run: python -m pip install --upgrade bump2version

      - name: Set Git identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Bump version
        run: |
          bump2version patch --allow-dirty
          git add pyproject.toml
          git commit -m "Bump version [skip ci]"
          git tag v$(grep -Po '(?<=version = \")[^\"]*' pyproject.toml)
          git push origin main --tags
